
project_id = "szbqmovulttttcuykyee"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
op_port = 54326
smtp_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
file_transform_enabled = true

[auth]
enabled = true
port = 54329
site_url = "http://localhost:5173"
additional_redirect_urls = [
  "https://localhost:5173", 
  "http://127.0.0.1:5173", 
  "https://127.0.0.1:5173", 
  "https://szbqmovulttttcuykyee.supabase.co/auth/v1/callback", 
  "http://localhost:5173/chat",
  "http://localhost:5173/login",
  "http://localhost:5173/reset-password"
]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true
# Fix OTP expiry - reduce from default to recommended threshold
otp_expiry = 600
# Enable leaked password protection
password_min_length = 8
enable_leaked_password_protection = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
# Set OTP expiry for email OTP as well
otp_expiry = 600

[auth.sms]
enable_signup = false
enable_confirmations = false
# Set OTP expiry for SMS OTP as well
otp_expiry = 600

[functions.encryption]
verify_jwt = true

[functions.mfa]
verify_jwt = true

[functions.file-upload]
verify_jwt = true

[functions.audit-logs]
verify_jwt = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
